In [5]:
import pandas as pd
df=pd.read_csv('cmlr.csv')
df.head()

selling_price  km_driven  car_age
0         450000     145500        7
1         700000      50000        3
2         550000      70000        8
3         500000     120000        7
4         360000     158000        9

In [6]:
df.shape

(129, 3)

In [7]:
X = df.iloc[:, 1:3].values 
X

array([[145500,      7],
       [ 50000,      3],
       [ 70000,      8],
       [120000,      7],
       [158000,      9],
       [ 25000,      4],
       [ 60000,      5],
       [ 90000,      6],
       [120000,      8],
       [147000,      5],
       [ 30000,      2],
       [ 30000,      5],
       [ 15000,      3],
       [ 80000,      7],
       [ 40000,      4],
       [107000,      4],
       [ 43000,      4],
       [108000,      9],
       [100000,      3],
       [ 25000,      2],
       [ 35000,      4],
       [ 80000,      7],
       [110000,      7],
       [100000,      7],
       [120000,      8],
       [ 70000,      5],
       [120000,      6],
       [ 40000,      5],
       [ 80000,      5],
       [ 35500,      3],
       [ 50000,      7],
       [ 20000,      4],
       [110000,      6],
       [ 30000,      6],
       [ 80000,      8],
       [127000,      4],
       [ 58000,      8],
       [ 60000,      6],
       [ 55000,      5],
       [ 50000,      4],


In [8]:
y=df.iloc[:,0].values
y

array([450000, 700000, 550000, 500000, 360000, 650000, 550000, 480000,
       530000, 600000, 700000, 561000, 755000, 420000, 680000, 620000,
       625000, 415000, 811000, 757000, 711000, 450000, 509999, 511000,
       450000, 649000, 500000, 525000, 600000, 650000, 650000, 650000,
       470000, 480000, 480000, 605000, 520000, 600000, 660000, 700000,
       550000, 750000, 680000, 525000, 650000, 520000, 610000, 651000,
       490000, 680000, 570000, 635000, 480000, 409999, 500000, 700000,
       420000, 650000, 470000, 550000, 699000, 415000, 530000, 625000,
       550000, 800000, 438999, 480000, 550000, 550000, 550000, 694000,
       450000, 700000, 580000, 750000, 600000, 675000, 625000, 430000,
       620000, 700000, 605000, 500000, 754000, 725000, 631000, 530000,
       675000, 745000, 669000, 600000, 740000, 440000, 409999, 465000,
       470000, 755000, 434999, 700000, 615000, 605000, 520000, 525000,
       700000, 625000, 650000, 395000, 465000, 360000, 600000, 720000,
      

In [22]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = \
train_test_split(X, y, test_size=0.20, random_state=6)

In [23]:
X_train[:5]

array([[100000,      6],
       [110000,      6],
       [100000,      8],
       [ 50000,      4],
       [108000,      9]], dtype=int64)

In [24]:
X_test[:5]

array([[100000,      8],
       [ 70000,      8],
       [120000,      7],
       [ 70000,      4],
       [127000,      4]], dtype=int64)

In [28]:
X_test.shape

(26, 2)

In [25]:
# Fitting Simple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)# x years --> y Rs salary

LinearRegression()

In [32]:
X_test[:5]

array([[100000,      8],
       [ 70000,      8],
       [120000,      7],
       [ 70000,      4],
       [127000,      4]], dtype=int64)

In [30]:
y_pred=model.predict(X_test)

In [33]:
y_pred

array([456078.00996115, 467328.09356251, 494956.52000463, 652842.35667341,
       631467.19783082, 662967.43191463, 471828.12700305, 567585.2808522 ,
       478578.17716387, 575085.33658644, 456078.00996115, 560085.22511796,
       712346.01998605, 509956.63147311, 448577.95422691, 454202.99602759,
       454202.99602759, 483706.43640327, 631467.19783082, 617713.87449704,
       652842.35667341, 665967.45420833, 768099.65543158, 450077.96537376,
       469953.11306949, 387949.28255413])

In [34]:
y_test

array([409999, 550000, 465000, 650000, 605000, 625000, 520000, 600000,
       530000, 480000, 390000, 520000, 800000, 420000, 530000, 420000,
       420000, 409999, 605000, 525000, 625000, 745000, 754000, 525000,
       430000, 360000], dtype=int64)

In [35]:
from sklearn.metrics import mean_absolute_error, \
mean_squared_error,r2_score

In [36]:
print(mean_absolute_error(y_test,y_pred))

51667.982910059574


In [37]:
print(mean_squared_error(y_test,y_pred))

3373842641.932638


In [39]:
import math
print(math.sqrt(mean_squared_error(y_test,y_pred)))

58084.788386742344


In [40]:
print(r2_score(y_test,y_pred))

0.7480658682311465


In [58]:
from sklearn.preprocessing import MinMaxScaler

In [59]:
s=MinMaxScaler()

In [60]:
X=s.fit_transform(X)

In [62]:
y=y.reshape(-1,1)
y=s.fit_transform(y)
y

array([[0.19955654],
       [0.75388027],
       [0.42128603],
       [0.31042129],
       [0.        ],
       [0.64301552],
       [0.42128603],
       [0.26607539],
       [0.37694013],
       [0.53215078],
       [0.75388027],
       [0.44567627],
       [0.87583149],
       [0.13303769],
       [0.70953437],
       [0.57649667],
       [0.58758315],
       [0.12195122],
       [1.        ],
       [0.88026608],
       [0.77827051],
       [0.19955654],
       [0.33259202],
       [0.33481153],
       [0.19955654],
       [0.64079823],
       [0.31042129],
       [0.36585366],
       [0.53215078],
       [0.64301552],
       [0.64301552],
       [0.64301552],
       [0.24390244],
       [0.26607539],
       [0.26607539],
       [0.54323725],
       [0.35476718],
       [0.53215078],
       [0.66518847],
       [0.75388027],
       [0.42128603],
       [0.86474501],
       [0.70953437],
       [0.36585366],
       [0.64301552],
       [0.35476718],
       [0.55432373],
       [0.645

In [ ]:
# Fitting Simple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)# x years --> y Rs salary
LinearRegression()


In [64]:
# Fitting Simple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)# x years --> y Rs salary

LinearRegression()

In [65]:
# Predicting the Test set results
y_pred = model.predict(X_test)
y_pred#y_hat

array([[0.65142905],
       [0.39195594],
       [0.21280443],
       [0.34827823],
       [0.90516489],
       [0.77542834],
       [0.89369038],
       [0.24722796],
       [0.59627683],
       [0.46080302],
       [0.1898554 ],
       [0.60897335],
       [0.1898554 ],
       [0.33680372],
       [0.4493285 ],
       [0.33565627],
       [0.68585258],
       [0.33680372],
       [0.10257454],
       [0.42637948],
       [0.33680372],
       [0.34827823],
       [0.40343045],
       [0.70880161],
       [0.67437807],
       [0.20706717]])

In [66]:
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score
print("MAE test score:", mean_absolute_error(y_test, y_pred))
print("MSE test score:", mean_squared_error(y_test, y_pred))

print("r2 test score:", r2_score(y_test, y_pred))
#adjusted r2 square

MAE test score: 0.09375293507340846
MSE test score: 0.012670160700910083
r2 test score: 0.7636188296797958


In [67]:
import numpy as np
Xnew = np.array([[8000,2]])
Xnew= s.fit_transform(Xnew)
ynew= model.predict(Xnew)


ValueError: non-broadcastable output operand with shape (1,1) doesn't match the broadcast shape (1,2)

In [69]:
ynew

array([[0.92237666]])

In [ ]:
#invert normalize
ynew = s.inverse_transform(ynew) 
Xnew = s.inverse_transform(Xnew)
print("X=",Xnew[0],"y=", ynew[0])

In [52]:
a=np.array([[18000,3]])

In [53]:
a

array([[18000,     3]])

In [54]:
a= s.fit_transform(a)
a

array([[0., 0.]])